/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccessService } from "../access.service";
import { AccessCreateInput } from "./AccessCreateInput";
import { Access } from "./Access";
import { AccessFindManyArgs } from "./AccessFindManyArgs";
import { AccessWhereUniqueInput } from "./AccessWhereUniqueInput";
import { AccessUpdateInput } from "./AccessUpdateInput";
import { PolicyFindManyArgs } from "../../policy/base/PolicyFindManyArgs";
import { Policy } from "../../policy/base/Policy";
import { PolicyWhereUniqueInput } from "../../policy/base/PolicyWhereUniqueInput";

export class AccessControllerBase {
  constructor(protected readonly service: AccessService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Access })
  async createAccess(@common.Body() data: AccessCreateInput): Promise<Access> {
    return await this.service.createAccess({
      data: data,
      select: {
        accessType: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Access] })
  @ApiNestedQuery(AccessFindManyArgs)
  async accesses(@common.Req() request: Request): Promise<Access[]> {
    const args = plainToClass(AccessFindManyArgs, request.query);
    return this.service.accesses({
      ...args,
      select: {
        accessType: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Access })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async access(
    @common.Param() params: AccessWhereUniqueInput
  ): Promise<Access | null> {
    const result = await this.service.access({
      where: params,
      select: {
        accessType: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Access })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccess(
    @common.Param() params: AccessWhereUniqueInput,
    @common.Body() data: AccessUpdateInput
  ): Promise<Access | null> {
    try {
      return await this.service.updateAccess({
        where: params,
        data: data,
        select: {
          accessType: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Access })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccess(
    @common.Param() params: AccessWhereUniqueInput
  ): Promise<Access | null> {
    try {
      return await this.service.deleteAccess({
        where: params,
        select: {
          accessType: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/policies")
  @ApiNestedQuery(PolicyFindManyArgs)
  async findPolicies(
    @common.Req() request: Request,
    @common.Param() params: AccessWhereUniqueInput
  ): Promise<Policy[]> {
    const query = plainToClass(PolicyFindManyArgs, request.query);
    const results = await this.service.findPolicies(params.id, {
      ...query,
      select: {
        access: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        policyName: true,
        rules: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/policies")
  async connectPolicies(
    @common.Param() params: AccessWhereUniqueInput,
    @common.Body() body: PolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policies: {
        connect: body,
      },
    };
    await this.service.updateAccess({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/policies")
  async updatePolicies(
    @common.Param() params: AccessWhereUniqueInput,
    @common.Body() body: PolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policies: {
        set: body,
      },
    };
    await this.service.updateAccess({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/policies")
  async disconnectPolicies(
    @common.Param() params: AccessWhereUniqueInput,
    @common.Body() body: PolicyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      policies: {
        disconnect: body,
      },
    };
    await this.service.updateAccess({
      where: params,
      data,
      select: { id: true },
    });
  }
}
